name: Deploy www.kestrun.dev

on:
  push:
    branches: [main]
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v4

      - name: 🗺️ Ensure sitemap & robots exist (if missing)
        run: |
          set -euo pipefail
          mkdir -p assets
          DOMAIN="https://www.kestrun.dev"
          # Create minimal robots.txt if absent
          if [ ! -f robots.txt ]; then
            cat > robots.txt <<'ROBOTS'
          User-agent: *
          Allow: /

          Sitemap: https://www.kestrun.dev/sitemap.xml
          Sitemap: https://docs.kestrun.dev/sitemap.xml
          Sitemap: https://blog.kestrun.dev/sitemap.xml
          Sitemap: https://coverage.kestrun.dev/sitemap.xml
          ROBOTS
                    fi
                    # Create minimal sitemap.xml if absent
                    if [ ! -f sitemap.xml ]; then
                      cat > sitemap.xml <<'SITEMAP'
          <?xml version="1.0" encoding="UTF-8"?>
          <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
            <url>
              <loc>https://www.kestrun.dev/</loc>
              <lastmod>2000-01-01</lastmod>
              <changefreq>weekly</changefreq>
              <priority>1.0</priority>
            </url>
            <url>
              <loc>https://docs.kestrun.dev/</loc>
              <lastmod>2000-01-01</lastmod>
              <changefreq>weekly</changefreq>
              <priority>0.9</priority>
            </url>
            <url>
              <loc>https://blog.kestrun.dev/</loc>
              <lastmod>2000-01-01</lastmod>
              <changefreq>weekly</changefreq>
              <priority>0.8</priority>
            </url>
            <url>
              <loc>https://coverage.kestrun.dev/</loc>
              <lastmod>2000-01-01</lastmod>
              <changefreq>daily</changefreq>
              <priority>0.5</priority>
            </url>
          </urlset>
          SITEMAP
          fi

      - name: 🗓️ Update <lastmod> to today (UTC)
        run: |
          set -euo pipefail
          DATE="$(date -u +%Y-%m-%d)"
          # replace every <lastmod>YYYY-MM-DD</lastmod> in sitemap.xml
          sed -E -i "s|(</?lastmod>)\\K[0-9]{4}-[0-9]{2}-[0-9]{2}|$DATE|g" sitemap.xml
          echo "Updated lastmod to $DATE"
          echo "-----"
          grep -n "<lastmod>" -n sitemap.xml || true

      - name: ⚙️ Configure Pages
        uses: actions/configure-pages@v5

      - name: 📦 Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./

      - name: 🚀 Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
